### ISSUE TITLE
Mejoras

### ISSUE THREAD

**Issue by migueldelmazo** [mariaozamiz/anonymous-proxy#1]
Muy buen trabajo @mariaozamiz!!!

Aquí tienes unos consejos para mejorar tu ejercicio:

Puntuación: 352 / 429
- [x] HTML > ATRIBUTOS: Todos los `img` deben tener el atributo `title`.
- [x] HTML > HERO: El texto del título del hero debe ser: Anonymous proxy.
- [x] HTML > MÓDULO LOOKING: Debe haber un elemento con el texto "Insomnia tips".
- [x] HTML > MÓDULO LOOKING: Debe haber un elemento con el texto "Insomnia tips" que sea un `H2 - H6`.
- [x] HTML > MÓDULO LOOKING: Debe haber un elemento con el texto "Looking through a window".
- [x] HTML > FOOTER: Necesitamos dos `ul` dentro de `nav`.

- [x] CSS > FOOTER: Alguno de los elementos del footer en tablet deben estar maquetado con flexbox > `order`.
- [x] CSS > TRANSICIONES: Debemos usar alguna transición CSS.

Es posible que cuando corrijas uno de estos puntos, otros se corrijan solos, ya que unos dependen de otros.

Y recuerda algo muy importante:

- Escribe tu código en inglés.
- Escribe todos los ficheros y carpetas en inglés.
- Los commits tambien tienen que ser en inglés empezando por un verbo en infinitivo.

Ánimo y si tienes cualquier duda avísame!!!

> Este issue ha sido creado automáticamente por ello puede tener algún error, si hay algo que no te encaja dímelo cuanto antes por favor.

> Para corregir el ejercicio buscamos determinadas palabras en el código para identificar las secciones. Por ejemplo buscamos **Anonymous** para buscar el hero. Si has escrito mal alguna palabra en el código es posible que te aparezcan aquí falsos errores.

Por favor no cierres este issue, ya lo haremos nosotros.

**Comment by mariaozamiz** [comment]
Hola Miguel

Le estoy echando un vistazo, te cuento:
- En el punto 2, creo que da error porque utilicé dos <span> dentro de un h1, de modo que el texto no está "completo".
- En los puntos 3 y 5, tengo entendido que le ha pasado a más compañeras, también busca el texto tal cual pero se lo ha encontrado en minúsculas (con text transform esto queda resuelto).
- En el footer ya tenía algo maquetado con order, no sé por qué salta o cómo puedo cambiarlo.
- También tengo las transiciones hechas pero en buttons... quizás lo buscaba en divs??

¡Ya me cuentas! Muchas gracias :)

**Comment by migueldelmazo** [comment]
Hola @mariaozamiz, te comento, en el punto 2 pedimos que la primera A esté en mayúsculas. Debemos escribir los contenidos con la gramática correcta. Al ser un título / frase empezamos con la primera en mayúsculas. En el punto 3 y 5 pasa lo mismo.

Respecto a [ ] CSS > FOOTER: Alguno de los elementos del footer en tablet deben estar maquetado con flexbox > `order`. Tienes toda la razón, ahí he metido la zarpa, lo corregiré.

Respecto a [ ] CSS > TRANSICIONES: Debemos usar alguna transición CSS. Lo que hace el auto corrector es buscar en http://beta.adalab.es/modulo-1-evaluacion-final-mariaozamiz/assets/css/main.css si existe la palabra transition y no existe. Supongo que no has hecho transiciones pero sí animaciones. Así que no te preocupes por esto, tu ejercicio está bien.

Muchas gracias por currarte las mejoras. Toma un gif para ti ![https://media.giphy.com/media/xT9IgtKSaY1ScFA0ta/giphy.gif](https://media.giphy.com/media/xT9IgtKSaY1ScFA0ta/giphy.gif)

**Comment by mariaozamiz** [comment]
Ahh!! Vale, ya entendí lo de los textos! 
¡¡Gracias!!
